language: rust
cache: cargo

matrix:
  include:
    # Required for the compile_error!() macro
    - rust: 1.20.0

    - rust: stable

    - env: FEATURES="--all-features"
      rust: nightly

script:
  - cargo build --verbose $FEATURES
  - cargo test --verbose $FEATURES
